-- MySQL Script generated by MySQL Workbench
-- 11/26/21 18:13:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema order
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema order
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `order` DEFAULT CHARACTER SET utf8 ;
USE `order` ;

-- -----------------------------------------------------
-- Table `order`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order`.`client` (
  `idclient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  PRIMARY KEY (`idclient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order`.`product` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order`.`order` (
  `idorder` INT NOT NULL AUTO_INCREMENT,
  `client_idclient` INT NOT NULL,
  `product_idproduct` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idorder`),
  INDEX `fk_order_client_idx` (`client_idclient` ASC),
  INDEX `fk_order_product1_idx` (`product_idproduct` ASC),
  CONSTRAINT `fk_order_client`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `order`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `order`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
