-- MySQL Script generated by MySQL Workbench
-- 11/26/21 23:31:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Magazin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Magazin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Magazin` DEFAULT CHARACTER SET utf8 ;
USE `Magazin` ;

-- -----------------------------------------------------
-- Table `Magazin`.`Otdel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Magazin`.`Otdel` (
  `idOtdel` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOtdel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Magazin`.`Tovar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Magazin`.`Tovar` (
  `idTovar` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `Otdel_idOtdel` INT NOT NULL,
  PRIMARY KEY (`idTovar`),
  INDEX `fk_Tovar_Otdel_idx` (`Otdel_idOtdel` ASC),
  CONSTRAINT `fk_Tovar_Otdel`
    FOREIGN KEY (`Otdel_idOtdel`)
    REFERENCES `Magazin`.`Otdel` (`idOtdel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
