-- MySQL Script generated by MySQL Workbench
-- 11/26/21 15:09:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Note
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Note
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Note` DEFAULT CHARACTER SET utf8 ;
USE `Note` ;

-- -----------------------------------------------------
-- Table `Note`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Note`.`User` (
  `idUser` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Note`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Note`.`note` (
  `idnote` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `text` VARCHAR(45) NOT NULL,
  `teg` VARCHAR(45) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idnote`),
  INDEX `fk_note_User_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_note_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Note`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
